# config/settings.toml
[window]
width = 800
height = 700
title = "ECS Dungeon Crawler"

[gameplay]
tile_size = 32
ui_height = 150
default_vision_radius = 2
crit_multiplier = 2.0
seed = 42

[colors]
black = [0, 0, 0]
white = [255, 255, 255]
gray = [128, 128, 128]
red = [255, 0, 0]
green = [0, 255, 0]
blue = [0, 0, 255]
yellow = [255, 255, 0]
gold = [255, 215, 0]
purple = [128, 0, 128]
cyan = [0, 255, 255]
fog_color = [32, 32, 48]